#line 2 "src/c_lexer.yy.cpp"

#line 4 "src/c_lexer.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[298] =
    {   0,
       84,   84,   91,   89,    1,    2,   45,   89,   89,   47,
       40,   89,   37,   38,   41,   42,   55,   43,   39,   46,
       84,   89,   53,   79,   48,   54,   49,   52,   87,   87,
       87,   84,   84,   35,   36,   50,   87,   87,   87,   87,
       87,   87,   87,   87,   84,   87,   87,   87,   84,   87,
       87,   77,   51,   78,   44,   64,   86,    0,    0,    0,
        0,   69,   65,   74,    0,    0,    0,   67,   57,   70,
       58,   71,   56,    0,   85,    0,   68,   85,   83,   83,
        0,    0,   84,   84,    0,    0,   84,   84,   59,   61,
       63,   62,   60,   87,   87,   87,   84,   75,   87,   87,

       87,   87,   87,   87,   30,   87,   87,   87,   87,   87,
       87,   87,   31,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,    0,   76,   66,    0,    0,    0,
        0,    0,    0,    0,   80,   85,   85,    0,   85,   85,
       83,   83,    0,   83,   83,    0,   82,    0,   72,   73,
       85,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   24,   87,   84,    5,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,    0,    0,    0,    0,    0,    0,   81,    0,    0,
        0,    0,    0,    0,    0,   82,   82,    0,   84,   85,

        3,   87,   11,   15,   87,   87,   87,   87,    8,   12,
       87,   87,   28,    9,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   26,   87,   87,    0,    0,
        0,    0,    0,    0,    0,   83,   83,    0,    7,   19,
       87,   87,   87,   87,   20,   87,   87,   21,   87,   87,
       87,   87,   87,   87,   18,   87,   87,   33,    0,    0,
        0,    0,   82,   87,   87,    4,   16,   87,   17,   25,
       34,   32,    6,   10,   87,   87,   87,   88,    0,   87,
       27,   87,   14,   87,   87,    0,   23,   13,   22,   29,
        0,    0,    0,    0,    0,    0,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   21,   22,   23,   22,   24,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   31,   33,   34,   35,
       36,   36,   36,   37,   36,   38,   37,   36,   36,   36,
       37,   36,   36,   36,   39,   37,   36,   40,   36,   37,
       41,   42,   43,   44,   37,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   37,   54,   55,   56,   57,
       58,   59,   37,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    6,    1,    1,    1,    1,    1,    7,
        6,    6,    6,    6,    6,    8,    8,    8,    8,    8,
        1,    9,    1,    1,    5,    5,    6,    6,    6,    5,
        8,    8,    8,    8,    8,    8,   10,    8,    8,   10,
        8,   10,    8,   10,    8,    8,    8,    8,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[306] =
    {   0,
        0,    0,  638,  866,  866,  866,  609,   67,  632,  607,
       65,   59,  866,  866,  606,   70,  866,   67,   99,  599,
      132,  187,  866,  866,   48,  598,   63,  866,    0,    0,
      139,    0,   56,  866,  866,  596,  560,  562,   80,   50,
       48,   49,  563,   87,  562,  570,  115,  545,  119,  553,
      558,  193,  190,  210,  866,  866,    0,    0,  120,  543,
      227,  866,  866,  866,    0,  171,  542,  866,  866,  866,
      866,  866,  866,  584,  242,  265,  866,  248,  255,  309,
        0,  316,  866,  109,    0,  577,  167,  279,  571,  866,
      866,  866,  570,    0,    0,  347,    0,  866,  535,  547,

      534,  549,  535,  541,  527,  526,  522,  521,  524,  520,
      517,  557,    0,  515,  519,   83,  517,   34,   55,  520,
      513,   75,  129,  518,  362,  866,  866,    0,  406,  465,
      369,  334,  524,  583,  866,    0,  866,  378,  629,    0,
      866,  185,  545,  866,  235,  544,  367,  544,  866,  866,
      681,  506,  518,  513,  501,  135,  515,  507,  493,  485,
      491,  488,    0,  474,    0,    0,  480,  475,  463,  461,
      451,  457,  421,  419,  419,  425,  415,  419,  421,  417,
      400,  294,  412,  733,    0,  419,  448,    0,  424,  438,
      765,    0,  457,  432,  429,  866,  339,  426,  866,    0,

        0,  370,    0,    0,  361,  368,  356,  360,    0,    0,
      354,  351,    0,    0,  343,  335,  325,  310,  294,  298,
      299,  294,  286,  270,  271,    0,  258,  262,  471,  482,
        0,  301,  497,  516,    0,  866,  866,  275,    0,    0,
      226,  227,  229,  218,    0,  212,  200,    0,  206,  203,
      205,  181,  183,  177,    0,  168,  171,    0,  529,  213,
      235,  536,  866,  137,  137,    0,    0,  137,    0,    0,
        0,    0,    0,    0,  133,  120,   95,  866,  303,   97,
        0,   75,    0,   82,   57,  300,    0,    0,    0,    0,
      354,  404,  397,  461,  503,  172,  866,  813,  819,  829,

      839,  845,  847,  849,  855
    } ;

static yyconst flex_int16_t yy_def[306] =
    {   0,
      297,    1,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  298,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  299,  299,
      299,  299,  299,  297,  297,  297,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  297,  297,  297,  297,  297,  300,  300,  300,  300,
      297,  297,  297,  297,  301,  301,  301,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,   75,   21,  297,
       22,  297,  297,  297,  302,  297,  302,   21,  297,  297,
      297,  297,  297,  299,   31,  299,  299,  297,  299,  299,

      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  297,  297,  297,    8,  300,  297,
      297,  298,  301,  297,  297,   75,  297,  297,  297,   75,
      297,  297,  297,  297,  297,  297,  302,  297,  297,  297,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  129,  129,  300,  303,  184,  297,  301,  133,  133,
      301,  304,  191,  297,  297,  297,  297,  297,  297,  299,

      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  129,  129,
      129,  305,  133,  133,  133,  297,  297,  297,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  129,  305,
      305,  133,  297,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  297,  305,  299,
      299,  299,  299,  299,  299,  305,  299,  299,  299,  299,
      305,  305,  305,  305,  305,  305,    0,  297,  297,  297,

      297,  297,  297,  297,  297
    } ;

static yyconst flex_int16_t yy_nxt[939] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   29,   29,   29,   30,   32,   33,   29,
       34,    4,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   30,   44,   30,   45,   30,   30,   30,   30,   46,
       47,   48,   49,   50,   51,   30,   30,   30,   52,   53,
       54,   55,   57,   63,   89,   90,   58,   66,   66,   66,
       66,   66,   71,   69,  171,   59,   59,   59,   59,   59,
       92,   93,   64,   97,   72,   73,   58,   70,  104,  173,

       67,  172,  106,  109,  107,  290,  110,  105,   60,  112,
       97,   58,   58,  108,  174,   74,   58,   75,   75,   75,
       75,   75,   75,   58,  101,   83,   58,  177,   58,  289,
       58,  102,   76,  168,  288,  178,  113,  103,  129,  129,
      129,  129,  129,  114,  169,  287,   83,   76,   78,  285,
       79,   80,   80,   80,   80,   81,   97,   95,   95,   95,
       95,   95,   95,   83,   82,   76,  117,  118,  284,   83,
       84,   85,   96,   97,  278,  122,  119,  261,   83,  120,
       76,  179,  283,  180,   86,  282,   83,   96,   83,  133,
      133,  133,  133,  133,   84,  205,  206,   85,  281,  280,

       82,   87,   82,   78,   83,   88,   88,   88,   88,   88,
       88,  125,  125,  125,  125,  125,  125,  126,  261,   82,
       76,   83,  141,  277,  276,  275,   76,   83,  125,  125,
      125,  125,  125,  125,  274,   76,   83,  278,  279,  141,
      261,   76,  273,   76,   83,  131,  131,  131,  131,  131,
      131,  272,  271,  270,  141,   82,  269,   82,   76,  127,
      136,  136,  136,  136,  136,  136,  140,  140,  140,  140,
      140,  140,  144,  268,  267,   76,  137,  266,  138,  137,
      138,  265,  264,  139,  139,  139,  139,  139,  139,  144,
       76,  137,  141,  142,  297,  263,  137,   88,   81,   81,

       81,   81,  278,  291,  144,  261,  261,  143,  261,  141,
      258,  137,  229,  229,  229,  229,  229,  142,  297,  257,
      297,  256,  286,  286,  142,   78,  255,   79,   79,   79,
       79,   79,   88,  254,  125,  125,  125,  125,  125,  125,
      253,   82,   76,  188,  297,  252,  144,  145,   84,   76,
      251,  250,   66,   66,   66,   66,   66,   76,  249,  261,
      138,  146,  138,  144,   76,  151,  151,  151,  151,  151,
      151,  145,  187,  292,  292,   67,  196,   82,  145,   82,
      125,  125,  125,  125,  125,  125,  248,  131,  131,  131,
      131,  131,  131,  196,  247,   76,  139,  139,  139,  139,

      139,  139,  261,  246,  196,  197,  278,  293,  196,  261,
       76,   57,  245,  244,  243,  182,  294,  294,  242,  198,
      241,  196,  240,  239,  183,  183,  183,  183,  183,  197,
      230,  230,  230,  230,  230,  182,  197,  182,  182,  182,
      182,  182,  233,  233,  233,  233,  233,   60,  238,  237,
      182,  182,  236,  232,  228,  182,  234,  234,  234,  234,
      234,  227,  182,  278,  295,  182,  261,  182,  226,  182,
       57,  225,  224,  223,   58,  189,  189,  189,  189,  189,
      222,  221,  220,  184,  184,  184,  184,  184,  185,  230,
      230,  230,  230,  230,   58,  185,  185,  185,  185,  185,

      259,  259,  259,  259,  259,  219,   60,  218,  261,  186,
      186,  185,  185,  185,  186,  234,  234,  234,  234,  234,
      217,   58,  296,  296,   58,  216,   58,  215,   58,  189,
      214,  213,  212,  188,  262,  262,  262,  262,  262,  211,
      210,  209,  190,  190,  190,  190,  190,  259,  259,  259,
      259,  259,  208,  189,  262,  262,  262,  262,  262,  207,
      204,  203,  202,  201,  199,   67,  195,  194,  189,  189,
      181,  176,  175,  189,  170,  167,  166,  165,  164,  163,
      189,  162,  161,  189,  160,  189,  159,  189,   65,  158,
      157,  156,  188,  155,  154,  153,  152,  150,  149,  148,

      135,  191,  191,  191,  191,  191,  192,  134,  130,  124,
      123,  121,   65,  192,  192,  192,  192,  192,  116,  115,
      111,  100,   99,   98,   67,   91,   77,  193,  193,  192,
      192,  192,  193,   68,   62,   61,   56,  297,  297,   65,
      297,  297,   65,  297,   65,  297,   65,  139,  139,  139,
      139,  139,  139,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  137,  297,  297,  137,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  137,  297,
      297,  297,  297,  137,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  137,  151,

      151,  151,  151,  151,  151,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  200,  297,  297,  200,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      200,  297,  297,  297,  297,  200,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      137,  231,  231,  231,  231,  231,  182,  297,  297,  297,
      297,  297,  297,  182,  182,  182,  182,  182,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  182,  182,  182,
      182,  182,  182,  235,  235,  235,  235,  235,  189,  297,
      297,  297,  297,  297,  297,  189,  189,  189,  189,  189,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  189,
      189,  189,  189,  189,  189,   65,   65,   65,  297,   65,
      297,   65,   65,   94,   94,  297,   94,  297,   94,  128,
      297,  297,  128,  128,  128,  128,  128,  297,  128,  132,
      297,  132,  297,  132,  132,  132,  132,  297,  132,  147,
      147,   58,   58,   65,   65,  260,  297,  260,  260,  260,
      260,  260,  260,  260,  260,    3,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297
    } ;

static yyconst flex_int16_t yy_chk[939] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,   11,   25,   25,    8,   12,   12,   12,
       12,   12,   18,   16,  118,    8,    8,    8,    8,    8,
       27,   27,   11,   33,   18,   18,    8,   16,   40,  119,

       12,  118,   41,   42,   41,  285,   42,   40,    8,   44,
       33,    8,    8,   41,  119,   19,    8,   19,   19,   19,
       19,   19,   19,    8,   39,   33,    8,  122,    8,  284,
        8,   39,   19,  116,  282,  122,   44,   39,   59,   59,
       59,   59,   59,   44,  116,  280,   84,   19,   21,  277,
       21,   21,   21,   21,   21,   21,   49,   31,   31,   31,
       31,   31,   31,   84,   21,   21,   47,   47,  276,   21,
       21,   21,   31,   49,  296,   49,   47,  296,   84,   47,
       21,  123,  275,  123,   21,  268,   21,   31,   49,   66,
       66,   66,   66,   66,   21,  156,  156,   21,  265,  264,

       21,   21,   21,   22,   87,   22,   22,   22,   22,   22,
       22,   52,   52,   52,   52,   52,   52,   53,  260,   22,
       22,   87,  142,  257,  256,  254,   52,   53,   54,   54,
       54,   54,   54,   54,  253,   22,   87,  261,  261,  142,
      261,   52,  252,   54,   53,   61,   61,   61,   61,   61,
       61,  251,  250,  249,  142,   22,  247,   22,   54,   53,
       75,   75,   75,   75,   75,   75,   78,   78,   78,   78,
       78,   78,  145,  246,  244,   75,   75,  243,   76,   75,
       76,  242,  241,   76,   76,   76,   76,   76,   76,  145,
       75,   75,   79,   79,   79,  238,   75,   88,   88,   88,

       88,   88,  286,  286,  145,  286,  232,   79,  279,   79,
      228,   75,  182,  182,  182,  182,  182,   79,   88,  227,
       79,  225,  279,  279,   79,   80,  224,   80,   80,   80,
       80,   80,   80,  223,   82,   82,   82,   82,   82,   82,
      222,   80,   80,  132,   88,  221,   80,   80,   88,   82,
      220,  219,  132,  132,  132,  132,  132,   80,  218,  291,
       96,   80,   96,   80,   82,   96,   96,   96,   96,   96,
       96,   80,  131,  291,  291,  132,  197,   80,   80,   80,
      125,  125,  125,  125,  125,  125,  217,  131,  131,  131,
      131,  131,  131,  197,  216,  125,  138,  138,  138,  138,

      138,  138,  293,  215,  147,  147,  292,  292,  197,  292,
      125,  129,  212,  211,  208,  129,  293,  293,  207,  147,
      206,  147,  205,  202,  129,  129,  129,  129,  129,  147,
      183,  183,  183,  183,  183,  129,  147,  186,  186,  186,
      186,  186,  189,  189,  189,  189,  189,  129,  198,  195,
      129,  129,  194,  187,  181,  129,  190,  190,  190,  190,
      190,  180,  129,  294,  294,  129,  294,  129,  179,  129,
      130,  178,  177,  176,  130,  193,  193,  193,  193,  193,
      175,  174,  173,  130,  130,  130,  130,  130,  130,  229,
      229,  229,  229,  229,  130,  130,  130,  130,  130,  130,

      230,  230,  230,  230,  230,  172,  130,  171,  295,  130,
      130,  130,  130,  130,  130,  233,  233,  233,  233,  233,
      170,  130,  295,  295,  130,  169,  130,  168,  130,  133,
      167,  164,  162,  133,  234,  234,  234,  234,  234,  161,
      160,  159,  133,  133,  133,  133,  133,  259,  259,  259,
      259,  259,  158,  133,  262,  262,  262,  262,  262,  157,
      155,  154,  153,  152,  148,  133,  146,  143,  133,  133,
      124,  121,  120,  133,  117,  115,  114,  112,  111,  110,
      133,  109,  108,  133,  107,  133,  106,  133,  134,  105,
      104,  103,  134,  102,  101,  100,   99,   93,   89,   86,

       74,  134,  134,  134,  134,  134,  134,   67,   60,   51,
       50,   48,  134,  134,  134,  134,  134,  134,   46,   45,
       43,   38,   37,   36,  134,   26,   20,  134,  134,  134,
      134,  134,  134,   15,   10,    9,    7,    3,    0,  134,
        0,    0,  134,    0,  134,    0,  134,  139,  139,  139,
      139,  139,  139,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  139,    0,    0,  139,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  139,    0,
        0,    0,    0,  139,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  139,  151,

      151,  151,  151,  151,  151,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  151,    0,    0,  151,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      151,    0,    0,    0,    0,  151,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      151,  184,  184,  184,  184,  184,  184,    0,    0,    0,
        0,    0,    0,  184,  184,  184,  184,  184,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  184,  184,  184,
      184,  184,  184,  191,  191,  191,  191,  191,  191,    0,
        0,    0,    0,    0,    0,  191,  191,  191,  191,  191,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  191,
      191,  191,  191,  191,  191,  298,  298,  298,    0,  298,
        0,  298,  298,  299,  299,    0,  299,    0,  299,  300,
        0,    0,  300,  300,  300,  300,  300,    0,  300,  301,
        0,  301,    0,  301,  301,  301,  301,    0,  301,  302,
      302,  303,  303,  304,  304,  305,    0,  305,  305,  305,
      305,  305,  305,  305,  305,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/c_lexer.l"
#line 4 "src/c_lexer.l"
#include <stdio.h>
#include <stdint.h>
#include <string>
char* sourceFile = "\"\"";
int linenum = 1;
int sourceLineNo = 1;
std::string sourceLine;
/*************** Identifier***************/ 
/*************** Floating Point Constant ***************/ 
/*************** Integer Constant ***************/ 
/*************** Keyword Constant ***************/ 
/*************** Operator Constant ***************/ 
/*************** Character Constant ***************/ 
/*************** String Literal ***************/ 
/*************** Preprocessor Line***************/ 
#line 780 "src/c_lexer.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 56 "src/c_lexer.l"


#line 992 "src/c_lexer.yy.cpp"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 866 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 58 "src/c_lexer.l"

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 59 "src/c_lexer.l"
linenum++; sourceLineNo++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "src/c_lexer.l"
printf("%s Keyword TAuto %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "src/c_lexer.l"
printf("%s Keyword TDouble %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "src/c_lexer.l"
printf("%s Keyword TInt %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "src/c_lexer.l"
printf("%s Keyword TStruct %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "src/c_lexer.l"
printf("%s Keyword TBreak %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "src/c_lexer.l"
printf("%s Keyword TElse %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "src/c_lexer.l"
printf("%s Keyword TLong %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "src/c_lexer.l"
printf("%s Keyword TSwitch %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "src/c_lexer.l"
printf("%s Keyword TCase %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "src/c_lexer.l"
printf("%s Keyword TEnum %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "src/c_lexer.l"
printf("%s Keyword TRegister %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "src/c_lexer.l"
printf("%s Keyword TTypedef %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "src/c_lexer.l"
printf("%s Keyword TChar %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "src/c_lexer.l"
printf("%s Keyword TExtern %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "src/c_lexer.l"
printf("%s Keyword TReturn %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "src/c_lexer.l"
printf("%s Keyword TUnion %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 "src/c_lexer.l"
printf("%s Keyword TConst %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 "src/c_lexer.l"
printf("%s Keyword TFloat %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 79 "src/c_lexer.l"
printf("%s Keyword TShort %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 80 "src/c_lexer.l"
printf("%s Keyword TUnsigned %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 "src/c_lexer.l"
printf("%s Keyword TContinue %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "src/c_lexer.l"
printf("%s Keyword TFor %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 "src/c_lexer.l"
printf("%s Keyword TSigned %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "src/c_lexer.l"
printf("%s Keyword TVoid %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "src/c_lexer.l"
printf("%s Keyword TDefault %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 86 "src/c_lexer.l"
printf("%s Keyword TGoto %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "src/c_lexer.l"
printf("%s Keyword TVolatile %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 88 "src/c_lexer.l"
printf("%s Keyword TDo %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 89 "src/c_lexer.l"
printf("%s Keyword TIf %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "src/c_lexer.l"
printf("%s Keyword TStatic %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "src/c_lexer.l"
printf("%s Keyword TWhile %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "src/c_lexer.l"
printf("%s Operator TSizeof %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "src/c_lexer.l"
printf("%s Operator TOpenSqBracket %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "src/c_lexer.l"
printf("%s Operator TCloseSqBracket %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "src/c_lexer.l"
printf("%s Operator TOpenBracket %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "src/c_lexer.l"
printf("%s Operator TCloseBracket %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "src/c_lexer.l"
printf("%s Operator TDot %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "src/c_lexer.l"
printf("%s Operator TBitwiseAnd %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "src/c_lexer.l"
printf("%s Operator TStar %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 "src/c_lexer.l"
printf("%s Operator TPlus %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "src/c_lexer.l"
printf("%s Operator TMinus %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "src/c_lexer.l"
printf("%s Operator TTilde %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "src/c_lexer.l"
printf("%s Operator TBang %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "src/c_lexer.l"
printf("%s Operator TSlash %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "src/c_lexer.l"
printf("%s Operator TPercent %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "src/c_lexer.l"
printf("%s Operator TGreater %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "src/c_lexer.l"
printf("%s Operator TLess %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "src/c_lexer.l"
printf("%s Operator TCarat %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "src/c_lexer.l"
printf("%s Operator TPipe %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "src/c_lexer.l"
printf("%s Operator TQuestion %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "src/c_lexer.l"
printf("%s Operator TColon %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "src/c_lexer.l"
printf("%s Operator TAssign %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "src/c_lexer.l"
printf("%s Operator TComma %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "src/c_lexer.l"
printf("%s Operator TArrow %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "src/c_lexer.l"
printf("%s Operator TIncrement %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "src/c_lexer.l"
printf("%s Operator TDecrement %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "src/c_lexer.l"
printf("%s Operator TLeftShift %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "src/c_lexer.l"
printf("%s Operator TRightShift %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 122 "src/c_lexer.l"
printf("%s Operator TLessEqual %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 123 "src/c_lexer.l"
printf("%s Operator TGreaterEqual %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "src/c_lexer.l"
printf("%s Operator TEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 125 "src/c_lexer.l"
printf("%s Operator TNotEqual %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "src/c_lexer.l"
printf("%s Operator TLogicalAnd %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "src/c_lexer.l"
printf("%s Operator TLogicalOr %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 128 "src/c_lexer.l"
printf("%s Operator TStarEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "src/c_lexer.l"
printf("%s Operator TSlashEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "src/c_lexer.l"
printf("%s Operator TPercentEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 131 "src/c_lexer.l"
printf("%s Operator TPlusEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 132 "src/c_lexer.l"
printf("%s Operator TMinusEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 133 "src/c_lexer.l"
printf("%s Operator TLeftShiftEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 134 "src/c_lexer.l"
printf("%s Operator TRightShiftEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 135 "src/c_lexer.l"
printf("%s Operator TAndEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 136 "src/c_lexer.l"
printf("%s Operator TCaratEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 137 "src/c_lexer.l"
printf("%s Operator TPipeEquals %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 138 "src/c_lexer.l"
printf("%s Operator TOpenCurlyBrace %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 139 "src/c_lexer.l"
printf("%s Operator TCloseCurlyBrace %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 140 "src/c_lexer.l"
printf("%s Operator TSemicolon %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 141 "src/c_lexer.l"
printf("%s Operator TEllipsis %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 144 "src/c_lexer.l"
printf("%s Constant TCharConstant %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 145 "src/c_lexer.l"
printf("%s Constant THexInteger %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 146 "src/c_lexer.l"
printf("%s Constant TOctInteger %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 147 "src/c_lexer.l"
printf("%s Constant TDecInteger %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 148 "src/c_lexer.l"
printf("%s Constant TFloatingPoint %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 150 "src/c_lexer.l"
printf("%s StringLiteral TStringLiteral %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 152 "src/c_lexer.l"
printf("%s Identifier TIdentifier %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 88:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 155 "src/c_lexer.l"
{ 
					sourceLine = yytext; 	
					sourceLineNo = atoi(&yytext[2])-1; 							
					size_t startOfFileName = sourceLine.find_first_of('"'); 								
					size_t endOfFileName = sourceLine.find_last_of('"'); 								
					size_t fileNameSize = endOfFileName - startOfFileName; 								
					sourceFile = strdup(sourceLine.substr(startOfFileName,fileNameSize+1).c_str()); 															
				}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 164 "src/c_lexer.l"
printf("%s Invalid TInvalid %i %s %i\n",yytext ,linenum, sourceFile, sourceLineNo);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 166 "src/c_lexer.l"
ECHO;
	YY_BREAK
#line 1511 "src/c_lexer.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 166 "src/c_lexer.l"




int main()
{

    yylex();
           
    return 0;
}




